### ISSUE TITLE
Seed Coat metadata missing

### ISSUE THREAD

**Issue by sestaton** [almeidasilvaf/SoybeanAtlas_issues#1]
There is no metadata for seed coat (0 BioProjects, 0 BioSamples) though the count data for seed coat is present. 

It would be helpful if this metadata file was updated to support the count data for this data set.

**Comment by almeidasilvaf** [comment]
Hi, @sestaton 

Thank you for using the Soybean Expression Atlas and for reporting this issue! 

I will push an updated version that fixes this problem as soon as possible and let you know. In the meantime, if you want to have quick access to the sample metadata for seed coat samples, you can get them from Supplementary Table S2 in the publication, also available [here](https://github.com/almeidasilvaf/SEA_paper/blob/master/products/tables/final_metadata_classified_atlas_v2.tsv).

For example, if you're analyzing data with R code, you'd do:

``` r
# Read sample metadata for the GitHub repo associated with the publication

library(tidyverse)

seedcoat_metadata <- read_tsv(
    "https://raw.githubusercontent.com/almeidasilvaf/SEA_paper/master/products/tables/final_metadata_classified_atlas_v2.tsv",
    show_col_types = FALSE
) |>
    filter(Part == "seed coat")

# Inspect the first rows and dimentions of the data frame
head(seedcoat_metadata)
#> # A tibble: 6 × 15
#>   BioProject  BioSample Run   Experiment Part  Pubmed Study_title Study_abstract
#>   <chr>       <chr>     <chr> <chr>      <chr>  <dbl> <chr>       <chr>         
#> 1 PRJNA184365 SAMN0183… SRR6… SRX212259  seed… 2.36e7 Using RNA-… To understand…
#> 2 PRJNA197251 SAMN0204… SRR8… SRX265545  seed… 2.60e7 Gene Expre… We investigat…
#> 3 PRJNA197251 SAMN0204… SRR8… SRX265546  seed… 2.60e7 Gene Expre… We investigat…
#> 4 PRJNA197251 SAMN0204… SRR8… SRX265551  seed… 2.60e7 Gene Expre… We investigat…
#> 5 PRJNA197251 SAMN0204… SRR8… SRX265552  seed… 2.60e7 Gene Expre… We investigat…
#> 6 PRJNA197251 SAMN0204… SRR8… SRX265553  seed… 2.60e7 Gene Expre… We investigat…
#> # ℹ 7 more variables: Treatment <chr>, Cultivar <chr>, Instrument <chr>,
#> #   Layout <chr>, Selection_method <chr>, Origin <chr>, Date <dttm>
dim(seedcoat_metadata)
#> [1] 141  15
```

<sup>Created on 2023-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sestaton** [comment]
Thanks for the response @almeidasilvaf! The code is very useful and this will get me the information I need for this data.

**Comment by almeidasilvaf** [comment]
Fixed in the latest version of the Soybean Expression Atlas. :tada:
